In [3]:
import numpy as np

In [7]:
arr = np.array([1,2,3,4,5,6,7,8,9,0])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [8]:
print(arr)

[1 2 3 4 5 6 7 8 9 0]


In [9]:
ar = np.array((1,2,3,4,5,6,7,8,9,0))

In [10]:
print(ar)

[1 2 3 4 5 6 7 8 9 0]


In [12]:
import numpy as np

arr = np.array([
    [-1, 2, 0, 4],
    [4, -0.5, 6, 0],
    [2.6, 0, 7, 8],
    [3, -7, 4, 2.0]
])

print(arr)

[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


In [14]:
import numpy as np
a = np.array([[1,2],
              [3,4],
              [5,6]
              ])
b = np.array([[1,2],
              [4,5],
              [6,7]
              ])


sum_of_array = a + b

print(sum_of_array)

[[ 2  4]
 [ 7  9]
 [11 13]]
