In [12]:
a = [10, 20, 30, 40, 50, 60]

In [13]:
a

[10, 20, 30, 40, 50, 60]

In [14]:
a[0] = 100

In [15]:
a

[100, 20, 30, 40, 50, 60]

In [16]:
a[5] = 900

In [17]:
a

[100, 20, 30, 40, 50, 900]

In [19]:
a[9] = 1000

IndexError: list assignment index out of range

- cause the list has not the array, and the index are not valid.

In [20]:
# the list of the array is 
a[4] = 40000

- this is the mutable, 
- mutable means its changable array,
- if we put the value of the array  then if i want, then im change the value of the value...

In [21]:
a

[100, 20, 30, 40, 40000, 900]

In [14]:
abc = [100, 200, 300, 400 ,500, 600,700, 800, 900]

In [15]:
for i in range(abc):
    print(5)

TypeError: 'list' object cannot be interpreted as an integer

In [17]:
arr = [3,1,3,4,5,6,7,76,5,43543,56768,564356,78]

In [18]:
ans=[]
for i in arr:
    if i>5:
        ans.append(i)

In [20]:
ans

[6, 7, 76, 43543, 56768, 564356, 78]

In [21]:
import numpy as np
narr = np.array(arr)
narr

array([     3,      1,      3,      4,      5,      6,      7,     76,
            5,  43543,  56768, 564356,     78])

---
### Coditional selections
---

In [22]:
bool_arr = narr > 5

- Indexcing the numpy arr, and its integer.

In [23]:
narr[bool_arr]

array([     6,      7,     76,  43543,  56768, 564356,     78])

---
- In Directing
---

In [24]:
narr[narr > 5]

array([     6,      7,     76,  43543,  56768, 564356,     78])

- it use mainly savarel types
- it works saveral operations
- 

In [25]:
narr+10

array([    13,     11,     13,     14,     15,     16,     17,     86,
           15,  43553,  56778, 564366,     88])

In [26]:
narr * 2

array([      6,       2,       6,       8,      10,      12,      14,
           152,      10,   87086,  113536, 1128712,     156])

In [27]:
narr - 10

array([    -7,     -9,     -7,     -6,     -5,     -4,     -3,     66,
           -5,  43533,  56758, 564346,     68])

In [28]:
narr = np.arange(20)

In [29]:
narr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [30]:
narr / 10

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [31]:
narr / 0

/tmp/ipykernel_21394/38099738.py:1: RuntimeWarning: divide by zero encountered in divide
  narr / 0
/tmp/ipykernel_21394/38099738.py:1: RuntimeWarning: invalid value encountered in divide
  narr / 0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf])

In [32]:
20/0

ZeroDivisionError: division by zero