In [1]:
print("Hello,World")

Hello,World


## Import numpy

In [1]:
import numpy as np

In [2]:
np.__version__

'2.4.4'

---
### numpy mainly using handaling 2d array

In [3]:
arr = [1,2,3,4,5,6,7,8]
arr

[1, 2, 3, 4, 5, 6, 7, 8]

In [4]:
n_arr = np.array(arr)

In [5]:
n_arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
arr_2d = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
n_arr_2d = np.array(arr_2d)

In [8]:
n_arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
np.arange(10, 15)

array([10, 11, 12, 13, 14])

In [14]:
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])