In [2]:
print("Hello,World")

Hello,World


## Import numpy

- version check

In [3]:
# import numpy
import numpy as np

In [4]:
# version check
np.__version__

'2.4.4'

---
### numpy mainly using handaling 2d array

In [5]:
arr = [1,2,3,4,5,6,7,8]
arr

[1, 2, 3, 4, 5, 6, 7, 8]

In [6]:
n_arr = np.array(arr)

In [7]:
n_arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
arr_2d = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
n_arr_2d = np.array(arr_2d)

In [10]:
n_arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
np.arange(10, 15)

array([10, 11, 12, 13, 14])

In [13]:
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

In [14]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.zeros([4,4,4])

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [17]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.ones([4,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.ones([4,4,4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

the gap is equal same.. and num is same type of the equal.

In [20]:
np.linspace(start=10, stop=20, num=5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [21]:
np.ones([3,2,3])

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [22]:
np.arange(3,9)

array([3, 4, 5, 6, 7, 8])

In [23]:
def nup_py_as_np():
    return np.ones([3,3])

In [24]:
nup_py_as_np()

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
np.linspace(start=10, stop=20, num = 10)

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

## Identity Matrics


- all corner value in 1 and upper tringle and lower tringle is 0.

In [26]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### Random number

- generet of the 2d or 3d or any d number generate any number.

In [27]:
from numpy import random


### Q. Normal distribution and uniform distribution ?

- generate number

In [30]:
# the number is 0 to 1

# 10 rown and 2 column for the random number....

np.random.rand(10,2)

array([[0.82960545, 0.26129832],
       [0.46076503, 0.5347362 ],
       [0.08049507, 0.16068738],
       [0.85277529, 0.90086744],
       [0.52171613, 0.45834588],
       [0.5757716 , 0.43895765],
       [0.04653968, 0.13202913],
       [0.90318888, 0.2897688 ],
       [0.78108891, 0.67473318],
       [0.78969196, 0.20717095]])

* geenerate the negitive number

In [40]:
np.random.randn()

-0.3980288506126052

In [41]:
np.random.randn(5,3)

array([[ 0.57467772, -1.06254741,  1.16647321],
       [ 0.9725588 , -0.11698412,  1.18869181],
       [ 0.17788732, -0.48152529, -1.26880476],
       [-0.30961707, -0.07546554,  1.9323867 ],
       [-0.36193239,  0.31224509,  0.1657241 ]])

In [54]:
np.random.randint(10,21)

10

In [58]:
np.random.randint(10,21, size = 10)

array([20, 11, 11, 13, 15, 18, 16, 13, 17, 11])

- array or tuplee

In [64]:
np.random.randint(10, 1000000000000000, size=[5,2])

array([[239033669730232, 456678999320566],
       [ 92897824000204, 191723307679982],
       [837248160957371, 877962081225847],
       [293476138204188, 500244615950789],
       [126326287685146, 322177482080756]])

In [67]:
rarr = np.random.randint(10, 21, size=[8,5,5])

In [68]:
rarr.shape

(8, 5, 5)

In [69]:
rarr.reshape(12,3)

ValueError: cannot reshape array of size 200 into shape (12,3)

In [72]:
rarr.reshape(25,8)

array([[19, 17, 13, 20, 15, 12, 16, 20],
       [19, 17, 18, 12, 16, 17, 18, 19],
       [17, 13, 14, 13, 17, 20, 15, 11],
       [17, 15, 15, 15, 10, 19, 15, 17],
       [17, 10, 15, 16, 18, 10, 19, 14],
       [18, 14, 12, 15, 20, 19, 12, 14],
       [19, 10, 16, 17, 11, 19, 20, 17],
       [20, 11, 19, 11, 14, 10, 15, 10],
       [16, 18, 13, 14, 19, 14, 15, 18],
       [15, 19, 19, 16, 12, 20, 17, 20],
       [16, 10, 14, 18, 10, 13, 14, 11],
       [17, 14, 16, 13, 19, 15, 18, 20],
       [11, 19, 13, 20, 15, 14, 12, 20],
       [19, 19, 20, 20, 15, 20, 13, 11],
       [18, 15, 19, 12, 20, 10, 13, 10],
       [14, 14, 14, 19, 20, 14, 11, 19],
       [14, 13, 11, 18, 17, 19, 15, 13],
       [20, 17, 17, 19, 17, 17, 16, 14],
       [10, 14, 16, 11, 20, 20, 10, 17],
       [12, 18, 12, 19, 17, 12, 13, 10],
       [19, 14, 13, 20, 10, 16, 19, 20],
       [14, 12, 19, 20, 11, 18, 11, 20],
       [13, 20, 12, 15, 18, 16, 12, 17],
       [11, 19, 12, 12, 15, 15, 11, 19],
       [20, 17, 

In [73]:
rarr

array([[[19, 17, 13, 20, 15],
        [12, 16, 20, 19, 17],
        [18, 12, 16, 17, 18],
        [19, 17, 13, 14, 13],
        [17, 20, 15, 11, 17]],

       [[15, 15, 15, 10, 19],
        [15, 17, 17, 10, 15],
        [16, 18, 10, 19, 14],
        [18, 14, 12, 15, 20],
        [19, 12, 14, 19, 10]],

       [[16, 17, 11, 19, 20],
        [17, 20, 11, 19, 11],
        [14, 10, 15, 10, 16],
        [18, 13, 14, 19, 14],
        [15, 18, 15, 19, 19]],

       [[16, 12, 20, 17, 20],
        [16, 10, 14, 18, 10],
        [13, 14, 11, 17, 14],
        [16, 13, 19, 15, 18],
        [20, 11, 19, 13, 20]],

       [[15, 14, 12, 20, 19],
        [19, 20, 20, 15, 20],
        [13, 11, 18, 15, 19],
        [12, 20, 10, 13, 10],
        [14, 14, 14, 19, 20]],

       [[14, 11, 19, 14, 13],
        [11, 18, 17, 19, 15],
        [13, 20, 17, 17, 19],
        [17, 17, 16, 14, 10],
        [14, 16, 11, 20, 20]],

       [[10, 17, 12, 18, 12],
        [19, 17, 12, 13, 10],
        [19, 14, 13, 20, 10]

In [74]:
rarr.max()

np.int64(20)

In [76]:
rarr.min()

np.int64(10)