# Indexing and Slicing

In [2]:
import numpy as np

In [3]:
arr = np.arange(10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr[0]

np.int64(0)

In [6]:
arr[5]

np.int64(5)

In [7]:
arr[-1]

np.int64(9)

In [8]:
arr[-7]

np.int64(3)

#### Array slice
arr[start : stop]

In [9]:
arr[1 : 6]

array([1, 2, 3, 4, 5])

In [10]:
arr[4 : 7]

array([4, 5, 6])

In [12]:
arr[ 1: 7 : 3]

array([1, 4])

In [13]:
arr[4 : 9 : 2]

array([4, 6, 8])

In [15]:
print("Helo,World!")

Helo,World!


In [1]:
import numpy as np

In [2]:
ar = np.arange(20)

In [3]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
arr = ar

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [6]:
arr[-1]

np.int64(19)

In [7]:
arr[0]

np.int64(0)

In [8]:
arr[5 : 10]

array([5, 6, 7, 8, 9])

In [9]:
arr[7:20:3]

array([ 7, 10, 13, 16, 19])