# Indexing and Slicing

In [28]:
import numpy as np

In [29]:
arr = np.arange(10)

In [30]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr[0]

np.int64(0)

In [32]:
arr[5]

np.int64(5)

In [33]:
arr[-1]

np.int64(9)

In [34]:
arr[-7]

np.int64(3)

#### Array slice
arr[start : stop]

In [35]:
arr[1 : 6]

array([1, 2, 3, 4, 5])

In [36]:
arr[4 : 7]

array([4, 5, 6])

In [37]:
arr[ 1: 7 : 3]

array([1, 4])

In [38]:
arr[4 : 9 : 2]

array([4, 6, 8])

In [39]:
print("Helo,World!")

Helo,World!


In [40]:
import numpy as np

In [41]:
ar = np.arange(20)

In [42]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [43]:
arr = ar

In [44]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [45]:
arr[-1]

np.int64(19)

In [46]:
arr[0]

np.int64(0)

In [47]:
arr[5 : 10]

array([5, 6, 7, 8, 9])

In [48]:
arr[7:20:3]

array([ 7, 10, 13, 16, 19])

In [49]:
arr2 = arr[7 : 17]
arr2

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [50]:
arr2[4] = 99
arr2

array([ 7,  8,  9, 10, 99, 12, 13, 14, 15, 16])

- array prod casting

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 99, 12, 13, 14, 15, 16,
       17, 18, 19])

In [52]:
arr2[ : ] = 99
arr2

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99])