# Indexing and Slicing

In [57]:
import numpy as np

In [58]:
arr = np.arange(10)

In [59]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
arr[0]

np.int64(0)

In [61]:
arr[5]

np.int64(5)

In [62]:
arr[-1]

np.int64(9)

In [63]:
arr[-7]

np.int64(3)

#### Array slice
arr[start : stop]

In [64]:
arr[1 : 6]

array([1, 2, 3, 4, 5])

In [65]:
arr[4 : 7]

array([4, 5, 6])

In [66]:
arr[ 1: 7 : 3]

array([1, 4])

In [67]:
arr[4 : 9 : 2]

array([4, 6, 8])

In [68]:
print("Helo,World!")

Helo,World!


In [69]:
import numpy as np

In [70]:
ar = np.arange(20)

In [71]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [72]:
arr = ar

In [73]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [74]:
arr[-1]

np.int64(19)

In [75]:
arr[0]

np.int64(0)

In [76]:
arr[5 : 10]

array([5, 6, 7, 8, 9])

In [77]:
arr[7:20:3]

array([ 7, 10, 13, 16, 19])

In [78]:
arr2 = arr[7 : 17]
arr2

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [79]:
arr2[4] = 99
arr2

array([ 7,  8,  9, 10, 99, 12, 13, 14, 15, 16])

- array Brod casting

In [80]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 99, 12, 13, 14, 15, 16,
       17, 18, 19])

In [81]:
arr2[ : ] = 99
arr2

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [82]:
arr

array([ 0,  1,  2,  3,  4,  5,  6, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       17, 18, 19])

- main data should not be change, then use the .copy()  statement 

In [83]:
arr3 = arr[3:8].copy()
arr3

array([ 3,  4,  5,  6, 99])

In [84]:
arr3[ : ] = 169
arr3

array([169, 169, 169, 169, 169])

In [85]:
arr


array([ 0,  1,  2,  3,  4,  5,  6, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       17, 18, 19])