# Indexing and Slicing

In [2]:
import numpy as np

In [3]:
arr = np.arange(10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr[0]

np.int64(0)

In [6]:
arr[5]

np.int64(5)

In [7]:
arr[-1]

np.int64(9)

In [8]:
arr[-7]

np.int64(3)

#### Array slice
arr[start : stop]

In [9]:
arr[1 : 6]

array([1, 2, 3, 4, 5])

In [10]:
arr[4 : 7]

array([4, 5, 6])

In [11]:
arr[ 1: 7 : 3]

array([1, 4])

In [12]:
arr[4 : 9 : 2]

array([4, 6, 8])

In [13]:
print("Helo,World!")

Helo,World!


In [14]:
import numpy as np

In [15]:
ar = np.arange(20)

In [16]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
arr = ar

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [19]:
arr[-1]

np.int64(19)

In [20]:
arr[0]

np.int64(0)

In [21]:
arr[5 : 10]

array([5, 6, 7, 8, 9])

In [22]:
arr[7:20:3]

array([ 7, 10, 13, 16, 19])

In [23]:
arr2 = arr[7 : 17]
arr2

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [24]:
arr2[4] = 99
arr2

array([ 7,  8,  9, 10, 99, 12, 13, 14, 15, 16])

- array Brod casting

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 99, 12, 13, 14, 15, 16,
       17, 18, 19])

In [26]:
arr2[ : ] = 99
arr2

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       17, 18, 19])

- main data should not be change, then use the .copy()  statement 

In [28]:
arr3 = arr[3:8].copy()
arr3

array([ 3,  4,  5,  6, 99])

In [29]:
arr3[ : ] = 169
arr3

array([169, 169, 169, 169, 169])

In [30]:
arr


array([ 0,  1,  2,  3,  4,  5,  6, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       17, 18, 19])

# Matrix Indexcing and Slicing

In [33]:
import numpy as np
matrix = np.array([[1,2,3,4],[10,20,30,40],[100,200,300,400],[1000, 2000, 3000, 4000]])
matrix

array([[   1,    2,    3,    4],
       [  10,   20,   30,   40],
       [ 100,  200,  300,  400],
       [1000, 2000, 3000, 4000]])

In [34]:
third_row = matrix[2]
third_row

array([100, 200, 300, 400])

In [35]:
third_row[2]

np.int64(300)

In [36]:
matrix[2][2]

np.int64(300)

In [37]:
matrix[2,3]

np.int64(400)

In [38]:
matrix[4,2]

IndexError: index 4 is out of bounds for axis 0 with size 4