In [1]:
import numpy as np
import pandas as pd

In [9]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr[3]

3

In [11]:
arr[-1]

9

In [12]:
type(arr[0])

numpy.int64

In [14]:
# Array Slice
arr[4:6]

array([4, 5])

In [16]:
arr[7:8]

array([7])

In [17]:
arr[1:7:3]

array([1, 4])

In [18]:
import numpy as np

In [20]:
ar = np.arange(40)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [21]:
A = ar

In [22]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [23]:
ar[-1]

39

In [24]:
A[-2]

38